### ISSUE TITLE
Dodać uczenie w trybie serii, okienko "przypięte" do ekranu.

### ISSUE THREAD

**Issue by DariusTheFirst** [misiek3510/memento_v2#6]

**Comment by misiek3510** [comment]
Zajmę się tym zaraz po zrobieniu aktualizacji i migracji starego kodu.

**Comment by misiek3510** [comment]
Zrobione. Działa, nie zauważyłem jakiś błędów. Można to zamknąć?

**Comment by DariusTheFirst** [comment]
Well done :)
